### ISSUE TITLE
Trigger not working in 0.12.19 [Solved: Fix in comments]

### ISSUE THREAD

**Issue by charleshan** [argenos/nldates-obsidian#62]
Trigger not working in 0.12.19

I'm seeing this error in the dev console:
```
date-suggest.ts:35 Uncaught (in promise)

Uncaught (in promise) TypeError: _this.setInstructions is not a function
    at new DateSuggest (eval at <anonymous> (app.js:1), <anonymous>:6737:19)
    at NaturalLanguageDates.eval (eval at <anonymous> (app.js:1), <anonymous>:6971:52)
    at step (eval at <anonymous> (app.js:1), <anonymous>:72:23)
    at Object.eval [as next] (eval at <anonymous> (app.js:1), <anonymous>:53:53)
    at fulfilled (eval at <anonymous> (app.js:1), <anonymous>:43:58)
```

**Comment by djbowers** [comment]
Same issue here with NLD v0.6.0 and Obsidian v0.12.19

**Comment by furlan** [comment]
Yes, same issue here with NLD v0.6.0 and Obsidian v0.12.19

**Comment by Bolt124** [comment]
Same issue Obsididan v0.12.19

**Comment by arbri15** [comment]
Hello, 
I created a GitHub account just to comment for this specific issue because that is how much I use this plugin in my day to day. As the people above posted, plugin stopped working on v0.12.19.

Thank you for for the awesome plug in btw.  😁😁

**Comment by sethlester** [comment]
> Hello, I created a GitHub account just to comment for this specific issue because that is how much I use this plugin in my day to day. As the people above posted, plugin stopped working on v0.12.19.
> 
> Thank you for for the awesome plug in btw. 😁😁

Also use this everyday. 

Rolling the plugin back to 0.5.2 let me get back working again.

Release is here
https://github.com/argenos/nldates-obsidian/releases/tag/0.5.2

1. Close Obsidian
2. Download the ZIP, and copy the 2 files into your $VAULT$\.obsidian\plugins\nldates-obsidian directory
3. Open Obsidian

**Comment by arbri15** [comment]
> 

Hey @sethlester , thank you for the reply and the quick solution. 

I got the plugin to work again but now every time I hit the "@" to enable the plugin, I get a rectangular menu bar pop up which I never had. Prior to the bug, I had a minimal date suggest pop under what I was typing, think more of a spelling check. Minor inconvenience but very grateful to just have the main functionality be working again. 

Thank you!

**Comment by furlan** [comment]
It's working fine here as well.
Thanks!

**Comment by ashishbhateja** [comment]
this is still an issue for me. other than reverting to the previous version, is there a fix planned?

**Comment by thuringia** [comment]
It is working again, for me, using the current insider releases. Looks like a regression on Obsidian's end, not the plugin.

**Comment by ashishbhateja** [comment]
Thanks, I will wait for the Obsidian release update

**Comment by liamcain** [comment]
Hi, sorry for the confusion. 

This was an issue with the new version (that's only compatible with the Insider Build of Obsidian) from getting released a bit prematurely. We made a fix so that Obsidian will now find the correct version, but **if you have the wrong version installed, you'll need to uninstall the plugin and reinstall it from the Community Plugins store**. Sorry again about the mix-up!
